-- tts_logs 表
create table tts_logs (
    id bigint generated by default as identity primary key,
    text text not null,
    voice_id text,
    model text,
    duration float,
    created_at timestamp with time zone default timezone('utc'::text, now())
);

-- llm_logs 表
create table llm_logs (
    id bigint generated by default as identity primary key,
    prompt text not null,
    response text not null,
    model text,
    tokens_used int,
    duration float,
    created_at timestamp with time zone default timezone('utc'::text, now())
);

-- stt_logs 表
create table stt_logs (
    id bigint generated by default as identity primary key,
    audio_duration float,
    transcription text not null,
    model text,
    duration float,
    created_at timestamp with time zone default timezone('utc'::text, now())
);