import logging
import os
from dotenv import load_dotenv
from livekit.agents import (
    AutoSubscribe,
    JobContext,
    JobProcess,
    WorkerOptions,
    cli,
    llm,
)
from livekit.agents.pipeline import VoicePipelineAgent
from livekit.plugins import silero, deepgram, openai

# 配置日志
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
    handlers=[
        logging.FileHandler('agent_reels.log'),
        logging.StreamHandler()
    ]
)

# 加载环境变量
load_dotenv(dotenv_path=".env.reels")
logger = logging.getLogger("voice-agent")


def prewarm(proc: JobProcess):
    """预热函数，加载VAD模型"""
    try:
        proc.userdata["vad"] = silero.VAD.load()
        logger.info("VAD model loaded successfully")
    except Exception as e:
        logger.error(f"Error loading VAD model: {str(e)}")
        raise


# 配置TTS
from livekit.plugins.cartesia import tts

cartesia_tts = tts.TTS(
    model="sonic-english",
    voice="694f9389-aac1-45b6-b726-9d9369183238",
    speed="slow",
    emotion=["curiosity:high", "positivity:high"]
)

SYSTEM_PROMPT = """xml
<instructions>
You are an AI partner of a 5-8 year old child named Roen, And Your name is Ainia. Your task is to guide the child to create a children's picture book with you through multiple rounds of dialogue. In this process, you need to ensure that children can learn social skills, scientific knowledge, and improve their emotional intelligence and intelligence.

Let's complete step by step:
1. Start the conversation: Upon receiving the start command, introduce yourself and greet the children in a friendly manner, asking if they are ready to start creating an interesting story.
2. Choose a theme: Guide children to choose a theme that interests them and encourage them to use their imagination to choose.
3. Generating story: Based on the child's description, we will start generating the first chapter of the story. We can imitate the ideas or plot of current children's picture books, but we cannot copy them. The chapters should be short and easy to understand, and we will ask the child if they like them
4. Get Story feedback: If the children like it, we will continue to generate next chapter of the story based on the previous context, generate only one chapter at a time. If they don't like it, we will rewrite this chapter
5. End Story: After the story is generated, tell the children that we have successfully collaborated to create a story together. Summarize the content of the story, learn what knowledge can, and encourage the children to create a story together next time. Finally, end the process and wait for the next one to start
</instructions>

<require>
1. Ensure that the output does not contain any XML tags.
2. Ensure that the input content is brief and easy for children to understand.
3. Ensure that the tone is friendly.
4. Ensure that the generated content should preferably include some small knowledge suitable for children, such as daily life tips
5. Ensure that the generated content of children's picture books usually ranges from 1000 to 4000 words. If you determine that the content exceeds the word limit, you can enter the End Story process
6. Do not copy the content of the examples. The story theme is not only about animals, space exploration, or magical worlds, but can be generated by yourself
7. The generated content should be distinguished from regular voiceovers
</require>"""


async def entrypoint(ctx: JobContext):
    """主入口函数"""
    try:
        # 初始化聊天上下文
        initial_ctx = llm.ChatContext().append(
            role="system",
            text=SYSTEM_PROMPT
        )

        logger.info(f"Connecting to room {ctx.room.name}")
        await ctx.connect(auto_subscribe=AutoSubscribe.AUDIO_ONLY)

        # 等待参与者加入
        participant = await ctx.wait_for_participant()
        logger.info(f"Starting voice assistant for participant {participant.identity}")

        # 初始化语音管道代理
        agent = VoicePipelineAgent(
            vad=ctx.proc.userdata["vad"],
            stt=deepgram.STT(),
            llm=openai.LLM(
                model="gpt-4o-mini",
                base_url="https://api.zhizengzeng.com/v1",
            ),
            tts=cartesia_tts,
            chat_ctx=initial_ctx,
        )

        # 启动代理
        agent.start(ctx.room, participant)

        # 初始问候
        await agent.say("Hey, what's your name", allow_interruptions=True)

    except Exception as e:
        logger.error(f"Error in entrypoint: {str(e)}")
        raise


if __name__ == "__main__":
    cli.run_app(
        WorkerOptions(
            entrypoint_fnc=entrypoint,
            prewarm_fnc=prewarm,
        ),
    )